### ISSUE TITLE
suggestions for React Tutorial

### ISSUE THREAD

**Issue by ryancwalsh** [NEAR-Edu/welcome-track#2]
I'm reviewing https://welcome-track-frontend.onrender.com/Getting%20Started/React%20Tutorial#3-create-a-landing-page

1. When time allows, I think we should change it to do something other than wrapping. It's super confusing. In the short time, if time allows, maybe you could add least write a couple sentences about what is going on and what wrapping means.
2. I'd consider adding a line like `const isLoggedIn = Boolean(wallet && wallet.isSignedIn() && contract);` (if that is correct) so that then you can make the "Login with NEAR" button only appear when relevant (since otherwise it's confusing, especially to newbies). Such as `{isLoggedIn ? <></> : <button onClick={() => handleLogin()}>Login with NEAR</button>}`
3. Maybe for the `select` box, add some right margin like `style={{marginRight: '1rem'}}`
4. For section `#4` and beyond https://welcome-track-frontend.onrender.com/Getting%20Started/React%20Tutorial#4-wrap-near-on-form-submit I'd clarify (such as after "Next we'll add a form to wrap NEAR.") something like: "Go ahead and update your `src/App.jsx` to have the following contents now.
5. If you take any suggestions above that will change the line numbers, be sure to update the line numbers mentioned in the tutorial.

**Comment by encody** [comment]
Quickstart seems a little sparse, most of the content is just the code block, which could probably do with a little more explanation. Maybe inline comments in the code itself? Those would probably be useful in the CRA template regardless.

I made a few minor edits with regards to formatting and some awkward language. Otherwise it looks good. Maybe add a "Next Steps" section for where to go from here? As in, what features to implement next, what pages of the WT or docs might be useful to read next, etc.
